### PR TITLE
FE-31 FE-32 Create new editors and switch between them

### PR DESCRIPTION
**Pull request by gidonkatten**
Can create new editors and switch between open editors using the navbar. Naming is done automatically and is being used as a key currently - will work on generating a unique ID next. Left to do still:

- Naming
- Renaming
- Closing

### CODE REVIEW

**Review by tomproberts — COMMENTED** [review]
Brilliant stuff. Just wondering, is there a reason that we still have AbstractCanvas and all its implementations? ModelCanvas, DataCanvas etc. are all just empty classes, now that the abstract method has been replaced, so it just seems a bit odd to me...

**Comment by gidonkatten** [comment]
> Brilliant stuff. Just wondering, is there a reason that we still have AbstractCanvas and all its implementations? ModelCanvas, DataCanvas etc. are all just empty classes, now that the abstract method has been replaced, so it just seems a bit odd to me...

They can probably be removed. The reason why I didn't is that they may be useful in the future e.g. if we want to register different options to different canvases and maybe customise each canvas differently.

**Comment by tomproberts** [comment]
> > Brilliant stuff. Just wondering, is there a reason that we still have AbstractCanvas and all its implementations? ModelCanvas, DataCanvas etc. are all just empty classes, now that the abstract method has been replaced, so it just seems a bit odd to me...
> 
> They can probably be removed. The reason why I didn't is that they may be useful in the future e.g. if we want to register different options to different canvases and maybe customise each canvas differently.

I think they should be removed

**Comment by gidonkatten** [comment]
> > > Brilliant stuff. Just wondering, is there a reason that we still have AbstractCanvas and all its implementations? ModelCanvas, DataCanvas etc. are all just empty classes, now that the abstract method has been replaced, so it just seems a bit odd to me...
> > 
> > 
> > They can probably be removed. The reason why I didn't is that they may be useful in the future e.g. if we want to register different options to different canvases and maybe customise each canvas differently.
> 
> I think they should be removed

**Review by tomproberts — APPROVED** [review]
image

**Pull request merged**
