### PR TITLE
FE-67 Add Ace Editor to IDE Tab

### PR DESCRIPTION
**Pull request by lancelotblanchard**
This PR adds the Ace Editor to the IDE Tab of the Code Vault. It is now possible to edit the custom code of a Custom Node by clicking the "Enter Func" (name to change when we have the Functions Tab probably), and to type the code in the IDE.

Additionally, it adds one Mutation and one Getter to the Vuex State:

- **Getter** `nodeTriggeringCodeVault`: Returns the Custom node that triggered the entering of the Code Vault. If the user went to the Code Vault via the Navigation Sidebar, this will be `undefined`.
- **Mutation** `leaveCodeVault`: Sets the `inCodeVault` parameter of the state to `false`. Additionally, sets the `nodeTriggeringCodeVault` to `undefined`.

_TODO (CORE-58): The Custom Node isn't using a Baklava Option for the Inline Code anymore, but the internal state. We need to change the way we traverse the Baklava state in order to account for that._

### CODE REVIEW

**Review by gidonkatten — DISMISSED** [review]
Looks good to me!

Just to note that we are going to change what happens when you click on the button. Instead of going into the IDE, you will be taken to the other tab where you can select functions. Then if you would like to create a function, you would have to go to the IDE tab and save the function, at which point you can select the newly created function.

**Comment by lancelotblanchard** [comment]
@tomproberts do you want me to wait for your styling changes before we merge this PR or are you ok with merging it for now and having another PR for the styling?

**Comment by tomproberts** [comment]
> @tomproberts do you want me to wait for your styling changes before we merge this PR or are you ok with merging it for now and having another PR for the styling?

Sorry, I was busy. I'm just about to start styling!

**Comment by gidonkatten** [comment]
I was just thinking and I don't think we should have the getters and mutations for the codevault in the editor, rather things like whether we are in code vault can be in root state and maybe some of the mutations / getters as well. I am also created a new vuex module for functions so some of it can be moved there

**Review by tomproberts — COMMENTED** [review]
It all seems good to me, idk if you want to look at a few of the changes I made @lancelotblanchard ? Otherwise I'm happy to approve. @gidonkatten , are you happy with me having moved the setting for the linked node to the new Vuex module that you made, or do you think it would be better just in somewhere like `EditorManager` or something?

**Comment by lancelotblanchard** [comment]
Wow, I like your styling for the IDE congrats!!

**Comment by gidonkatten** [comment]
> It all seems good to me, idk if you want to look at a few of the changes I made @lancelotblanchard ? Otherwise I'm happy to approve. @gidonkatten , are you happy with me having moved the setting for the linked node to the new Vuex module that you made, or do you think it would be better just in somewhere like `EditorManager` or something?

Yes but I think leaving and entering the codevault should be a part of the root state instead of editor

**Comment by tomproberts** [comment]
> Yes but I think leaving and entering the codevault should be a part of the root state instead of editor

Decent, I'll do that then. I guess I thought that, because the `Editor` state kept track of which one was open and stuff, that it was suited for the UI stuff like `inCodeVault`, but I'll change it now.

**Comment by gidonkatten** [comment]
I also get compilation errors when I try and run locally

**Comment by tomproberts** [comment]
> I also get compilation errors when I try and run locally

Which files? Have you done `npm install`? I'm just surprised that the compile checks on CI haven't picked up on it...

**Comment by gidonkatten** [comment]
> > I also get compilation errors when I try and run locally
> 
> Which files?

Nevermind, it was just that I need to install a package

**Review by gidonkatten — APPROVED** [review]

**Pull request merged**
