### PR TITLE
FE-64 Implemented CodeVault skeleton.

### PR DESCRIPTION
**Pull request by tomproberts**
Created a new 'editor' on the navbar for the code vault. Updated state to have a `inCodeVault` field so that there remains a link between the `currEditor` for Baklava, and the code vault (e.g. when doing things with `CustomNode`s). Implemented the basic tab interface.

### CODE REVIEW

**Review by lancelotblanchard — DISMISSED** [review]
Looks amazing, congrats! 👏 
One small thing: When you are in the Code Vault tab and you create a new Editor (Model, Data or Training), the Code Vault is not exited and you need to click on the Editor name to change views. I think that to echo the behaviour of Creating an Editor while on another tab, we should make the view change automatically. Thoughts, @gidonkatten ?

**Comment by gidonkatten** [comment]
> Looks amazing, congrats! 
> One small thing: When you are in the Code Vault tab and you create a new Editor (Model, Data or Training), the Code Vault is not exited and you need to click on the Editor name to change views. I think that to echo the behaviour of Creating an Editor while on another tab, we should make the view change automatically. Thoughts, @gidonkatten ?

I agree

**Comment by gidonkatten** [comment]
Another thing is that the accept cookies prompt is covering the code vault button so if you never click on accept then you will not know about the code vault

**Comment by tomproberts** [comment]
> Looks amazing, congrats! 👏
> One small thing: When you are in the Code Vault tab and you create a new Editor (Model, Data or Training), the Code Vault is not exited and you need to click on the Editor name to change views. I think that to echo the behaviour of Creating an Editor while on another tab, we should make the view change automatically. Thoughts, @gidonkatten ?

I'll take a look

**Comment by tomproberts** [comment]
> Another thing is that the accept cookies prompt is covering the code vault button so if you never click on accept then you will not know about the code vault

Is that really an issue tho, if you don't want to accept cookies then you shouldn't be using it. It's not really a trivial fix either, so imo we shouldn't entertain that 'use case'. Thoughts?

**Comment by lancelotblanchard** [comment]
> > Another thing is that the accept cookies prompt is covering the code vault button so if you never click on accept then you will not know about the code vault
> 
> Is that really an issue tho, if you don't want to accept cookies then you shouldn't be using it. It's not really a trivial fix either, so imo we shouldn't entertain that 'use case'. Thoughts?

I agree!

**Review by lancelotblanchard — APPROVED** [review]
Looks good to me!

**Pull request merged**
