### PR TITLE
FE35 Fixed Sidebar tab width and viewport issue.

### PR DESCRIPTION
**Pull request by tomproberts**
Bug fix, involved keeping track with javascript of maximum width. Included sidebar width private field, in order that it may be used when sidebar collapsing/minimising is implemented.

### CODE REVIEW

**Comment by tomproberts** [comment]
So we still technically have issues if you zoom to 250% but that's a whole UI thing where components will break each other. I figured that in practice everything is fine now at all standard resolutions (even on my phone). If it's still an issue, I should probably overhall the whole UI to make it work at all weird resolutions, but IMO that's a lot of work for not very much gain.

Maybe an issue that should be addressed in the distant future?

**Comment by gidonkatten** [comment]
> So we still technically have issues if you zoom to 250% but that's a whole UI thing where components will break each other. I figured that in practice everything is fine now at all standard resolutions (even on my phone). If it's still an issue, I should probably overhall the whole UI to make it work at all weird resolutions, but IMO that's a lot of work for not very much gain.
> 
> Maybe an issue that should be addressed in the distant future?

 When I tried it out, the sidebar breaks at 200% but everything else works, then at 400% the titlebar text and a button moves to a second line (which is just visual). What it the UI thing where components break each other because I can't see that?

**Review by lancelotblanchard — DISMISSED** [review]
Looks good to me for the code!

**Comment by gidonkatten** [comment]
> > So we still technically have issues if you zoom to 250% but that's a whole UI thing where components will break each other. I figured that in practice everything is fine now at all standard resolutions (even on my phone). If it's still an issue, I should probably overhall the whole UI to make it work at all weird resolutions, but IMO that's a lot of work for not very much gain.
> > Maybe an issue that should be addressed in the distant future?
> 
> When I tried it out, the sidebar breaks at 200% but everything else works, then at 400% the titlebar text and a button moves to a second line (which is just visual). What it the UI thing where components break each other because I can't see that?

I am happy to approve as this moves as in the right direction but I think we should try and make all components robust to these things.

**Review by gidonkatten — DISMISSED** [review]

**Review by gidonkatten — APPROVED** [review]

**Pull request merged**
